// Validates the Dart BoT-SORT port against recorded output from the Python
// reference implementation (`BoT-SORT/tracker/{kalman_filter,matching,
// bot_sort}.py`), per `mobile/sub-plans/02-botsort-port.md` step 4: this is
// the actual acceptance criterion for the port, not the unit tests
// elsewhere in this directory.
//
// The fixture JSON is generated by running
// `tracking-validation/notebooks/generate_reference_fixtures.ipynb`
// yourself (never executed by the assistant, per this repo's `CLAUDE.md`)
// and is not checked in — this test skips gracefully with a clear message
// until that's been done at least once.
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:reefsight_mobile/tracking/bot_sort_tracker.dart';
import 'package:reefsight_mobile/tracking/tracker_detection.dart';

void main() {
  final fixturesDir = Directory('test/tracking/fixtures');
  final fixtureFiles = fixturesDir.existsSync()
      ? fixturesDir
          .listSync()
          .whereType<File>()
          .where((f) => f.path.endsWith('.json'))
          .toList()
      : <File>[];

  if (fixtureFiles.isEmpty) {
    test(
      'reference parity fixtures not yet generated',
      () {},
      skip: 'Run tracking-validation/notebooks/generate_reference_fixtures.ipynb '
          'and re-run this test — see mobile/sub-plans/02-botsort-port.md step 4.',
    );
    return;
  }

  for (final file in fixtureFiles) {
    final name = file.uri.pathSegments.last.replaceAll('.json', '');

    test('matches the Python reference on "$name"', () {
      final fixture = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
      final config = fixture['config'] as Map<String, dynamic>;
      final frames = fixture['frames'] as List<dynamic>;

      final tracker = BoTSortTracker(
        trackHighThresh: (config['trackHighThresh'] as num).toDouble(),
        trackLowThresh: (config['trackLowThresh'] as num).toDouble(),
        newTrackThresh: (config['newTrackThresh'] as num).toDouble(),
        trackBuffer: config['trackBuffer'] as int,
        matchThresh: (config['matchThresh'] as num).toDouble(),
        fuseScore: config['fuseScore'] as bool,
      );

      for (var frameIndex = 0; frameIndex < frames.length; frameIndex++) {
        final frame = frames[frameIndex] as Map<String, dynamic>;
        final detections = (frame['detections'] as List<dynamic>)
            .map((d) => d as Map<String, dynamic>)
            .map(
              (d) => TrackerDetection(
                x1: (d['x1'] as num).toDouble(),
                y1: (d['y1'] as num).toDouble(),
                x2: (d['x2'] as num).toDouble(),
                y2: (d['y2'] as num).toDouble(),
                score: (d['score'] as num).toDouble(),
              ),
            )
            .toList();

        final actual = tracker.update(detections);
        final expected = (frame['expected_tracks'] as List<dynamic>)
            .map((t) => t as Map<String, dynamic>)
            .toList();

        expect(
          actual.map((t) => t.trackId).toList(),
          expected.map((t) => t['track_id'] as int).toList(),
          reason: 'track id mismatch on frame $frameIndex of "$name"',
        );

        for (var i = 0; i < actual.length; i++) {
          final actualTlbr = actual[i].tlbr;
          final expectedTlbr = (expected[i]['tlbr'] as List<dynamic>)
              .map((v) => (v as num).toDouble())
              .toList();
          for (var c = 0; c < 4; c++) {
            expect(
              actualTlbr[c],
              closeTo(expectedTlbr[c], 1e-6),
              reason:
                  'tlbr[$c] mismatch on frame $frameIndex, track ${actual[i].trackId} of "$name"',
            );
          }
        }
      }
    });
  }
}
